query {
  recipes (status: "PUBLISHED") {
    data {
      id
      title
      slug
      image
      difficulty
      prep_time
      status
      country {
        id
        name
        native
        emoji
        iso3
      }
      state {
        id
        name
      }
      author {
        id
        name
        username
      }
      meals {
        id
        title
        slug
      }
    }
  }
}
