query($slug: ID!) {
  recipe(slug: $slug) {
    id
    title
    slug
    difficulty
    prep_time
    image
    video
    ingredient_note
    status
    body
    meals {
      id
      title
    }
    author {
      id
      name
      username
      avatar
      info {
        id
        about
      }
      roles {
        id
        name
      }
      social {
        id
        link
        media {
          id
          name
          icon
        }
      }
    }
    categories {
      id
      title
    }
    steps {
      id
      step
    }
    ingredients {
      id
      amount
      note
      ingredient {
        id
        title
        slug
      }
    }
    notes {
      id
      body
    }
    images {
      id
      file
    }
  }
}
