query($slug: ID!) {
  recipe(slug: $slug) {
    id
    title
    slug
    difficulty
    prep_time
    serves
    image
    video
    ingredient_note
    status
    body
    meals {
      id
      title
    }
    author {
      id
      name
      username
      email_verified_at
      avatar
      info {
        id
        about
      }
      application {
        status
        channel_type
        channel_url
      }
      roles {
        id
        name
      }
      social {
        id
        link
        media {
          id
          name
          icon
        }
      }
    }
    categories {
      id
      title
    }
    steps {
      id
      step
      type
      order
    }
    ingredients {
      id
      amount
      note
      ingredient {
        id
        title
        slug
      }
    }
    notes {
      id
      body
    }
    images {
      id
      file
    }
    country {
      id
      name
      native
      emoji
      iso3
    }
    state {
      id
      name
    }
  }
}
