query($username: ID!) {
  userbyname(username: $username) {
    id
    name
    avatar
    info {
      id
      about
    }
    social {
      id
      link
      media {
        id
        name
        icon
      }
    }
    recipes {
      id
      title
      slug
      image
      difficulty
      prep_time
      author {
        id
        name
        username
      }
      meals {
        id
        title
        slug
      }
    }
  }
}
