query($username: ID!) {
  userbyname(username: $username) {
    id
    name
    username
    email_verified_at
    avatar
    application {
      status
      channel_type
      channel_url
    }
    info {
      id
      about
    }
    roles {
      id
      name
    }
    social {
      id
      link
      media {
        id
        name
        icon
      }
    }
    recipes {
      id
      title
      slug
      image
      difficulty
      prep_time
      status
      country {
        id
        name
        native
        emoji
        iso3
      }
      state {
        id
        name
      }
      author {
        id
        name
        username
        email_verified_at
        application {
          status
          channel_type
          channel_url
        }
      }
      meals {
        id
        title
        slug
      }
    }
  }
}
